/**
 * ILLUSTRATIVE SAMPLE DATA. NOT REAL.
 * Every row below is generated by a fixed formula so the charts, maps and explorer can be designed and tested.
 * Partner names are generic ("Partner A" ...) on purpose, so no figure can be mistaken for a real country statistic.
 * When verified datasets are approved, replace `sampleRows` (or load a CSV) and set `isSample` to false.
 */
export const isSample = true;

export const partners = ['Partner A', 'Partner B', 'Partner C', 'Partner D', 'Partner E', 'Partner F', 'Partner G', 'Partner H', 'Partner I', 'Partner J'] as const;
export const partnerRegion: Record<string, string> = {
  'Partner A': 'Africa', 'Partner B': 'Africa', 'Partner C': 'Middle East', 'Partner D': 'Asia-Pacific', 'Partner E': 'Asia-Pacific',
  'Partner F': 'Asia-Pacific', 'Partner G': 'Europe', 'Partner H': 'Europe', 'Partner I': 'Americas', 'Partner J': 'Americas',
};
export const regions = ['Africa', 'Middle East', 'Asia-Pacific', 'Europe', 'Americas'] as const;
export const sectors = ['Mining and minerals', 'Energy', 'Transport and logistics', 'Manufacturing and SEZs', 'Tourism and nature', 'Agriculture and food', 'Skills, health and water'] as const;
export const categories = ['Category A', 'Category B', 'Category C'] as const;
export const years = [2019, 2020, 2021, 2022, 2023, 2024] as const;
export const indicators = ['Trade value', 'Investment value'] as const;

export type Row = { p: string; r: string; y: number; s: string; c: string; i: (typeof indicators)[number]; v: number };

/** Small deterministic pseudo-random number (0..1) from a string, so the sample never changes between builds. */
function rand(key: string): number {
  let h = 2166136261;
  for (let k = 0; k < key.length; k++) { h ^= key.charCodeAt(k); h = Math.imul(h, 16777619); }
  h ^= h >>> 15; h = Math.imul(h, 2246822519); h ^= h >>> 13;
  return ((h >>> 0) % 10000) / 10000;
}

export const sampleRows: Row[] = (() => {
  const rows: Row[] = [];
  for (const p of partners) {
    for (const y of years) {
      const growth = 1 + 0.09 * (y - 2019) * (0.5 + rand(`g${p}`));
      rows.push({ p, r: partnerRegion[p], y, s: 'All sectors', c: 'All categories', i: 'Trade value',
        v: Math.round((25 + rand(`t${p}`) * 60) * growth * (0.9 + rand(`t${p}${y}`) * 0.2) * 10) / 10 });
      sectors.forEach((s, si) => {
        rows.push({ p, r: partnerRegion[p], y, s, c: categories[si % 3], i: 'Investment value',
          v: Math.round((4 + rand(`i${p}${s}`) * 14) * growth * (0.8 + rand(`i${p}${s}${y}`) * 0.4) * 10) / 10 });
      });
    }
  }
  return rows;
})();

export const datasetMeta = {
  id: 'sample-economic-diplomacy',
  title: 'Sample economic diplomacy dataset',
  source: 'None. Illustrative sample data generated for design and testing.',
  units: 'Illustrative index points (not currency)',
  period: '2019 to 2024 (sample years)',
  notes: 'Partners are generic placeholders. Replace with verified, sourced data before publication.',
  rows: sampleRows.length,
};

export const timelineTypes = ['State visit', 'Joint commission', 'New mission', 'Agreement signed', 'Summit'] as const;
export const sampleTimeline = timelineTypes.flatMap((t, i) => [
  { type: t, title: `${t}: sample entry`, date: `Sample date ${i * 2 + 1}`, text: 'Placeholder text. A real entry cites an official source and a date.' },
  { type: t, title: `${t}: sample entry`, date: `Sample date ${i * 2 + 2}`, text: 'Placeholder text. A real entry cites an official source and a date.' },
]).sort((a, b) => a.date.localeCompare(b.date, undefined, { numeric: true }));

/** Deterministic 0..99 illustrative value for a name (used for the sample map shading only). */
export const sampleIndex = (name: string) => Math.floor(rand(`map${name}`) * 100);
